ユーザーページのUI実装
shinonome-inc/flutter_app_qiita_ryunosuke pull request #19
Opened 2022-06-25 03:49 UTC by Ryunosuke1114

Userの情報を取ってきてUIに表示、Userに関連する記事の取得とその表示を実装しました。
お時間ある時にレビューお願いします！
<img src = 'https://user-images.githubusercontent.com/85178728/175757029-21947ccc-a5a5-4287-81d4-523c9beff90d.png' width = 200>

2022-06-27 05:37 UTC, KobayashiYoh requested changes
2点コメントしました。

2022-06-27 05:37 UTC, KobayashiYoh commented on lib/pages/user_page.dart
> +  Widget notLoginView() => const NotLoginPage();
この記述にはどういった役割があるのですか？

2022-06-27 05:37 UTC, KobayashiYoh commented on lib/pages/user_page.dart
> +  }
再読み込みが上手くできないのですが、そちらの環境では上手く再読み込みできていますか？
マイページでも同じように再読み込みができないという現象がみられました（今回の実装とは関係ないので今はマイページを修正する必要はありません）。

フォローページ・フォロワーページの再読み込み機能はしっかり実装できていました。

2022-06-28 05:11 UTC, Ryunosuke1114 commented on lib/pages/user_page.dart
> +  Widget notLoginView() => const NotLoginPage();
not_login_pageをただ関数にしているだけなのであんまり意味なかったので修正しました。

2022-06-28 05:25 UTC, Ryunosuke1114 commented on lib/pages/user_page.dart
> +  }
https://user-images.githubusercontent.com/85178728/176098977-1c39190b-2f33-469d-af7b-6e69d55b38d4.gif

https://user-images.githubusercontent.com/85178728/176099044-1b25ff27-af4a-4ec4-abd4-e8462406396a.gif

my_pageとuse_pageの記事とユーザー情報の再読み込みの部分を修正しました。
確認お願いします🙇

2022-06-29 01:23 UTC, Ryunosuke1114 commented on lib/pages/user_page.dart
> +  }
https://user-images.githubusercontent.com/85178728/176330709-c7990a72-f329-41a3-9f9a-aff55275616e.gif

setState追加して画面の再描画できるように修正しました。
またIndicatorが目にみないように修正しました。確認お願いします🙇

2022-06-29 02:00 UTC, KobayashiYoh commented
しっかり修正できています！
LGTMです！

2022-06-29 09:56 UTC, kota78 commented
.envファイルがどこにあるか分からない状態でしたので、Readmeに記載していただきたいです。
googledriveなどのリンクと、ダウンロードしたファイルをどこに保存するかを記載してください。
[こちら](https://github.com/shinonome-inc/mobile_shu_mogi_Qclient)を参考にしていただければと思います。

2022-06-29 15:39 UTC, kota78 commented on lib/components/user_page_article_list.dart
> +              ),
<img width="233" alt="スクリーンショット 2022-06-30 0 37 43" src="https://user-images.githubusercontent.com/82959924/176477882-fe0af1a8-d426-4d96-a3f6-a08a8eecff5e.png">
日本語と英語でフォントが違うためか、ずれが生じてしまっているようです。
[参考](https://qiita.com/najeira/items/467936cffe857ebf35e9)

2022-06-29 21:32 UTC, KobayashiYoh approved these changes

2022-06-30 02:05 UTC, Ryunosuke1114 commented on lib/components/user_page_article_list.dart
> +              ),
ズレというのはLGTMという文字列が少し投稿日よりも高い場所に位置しているということですか？？

2022-06-30 02:07 UTC, Ryunosuke1114 commented
Readme 編集しました。
.envファイルのダウンロードそちらからお願いします🙇

2022-06-30 05:05 UTC, Ryunosuke1114 commented
fontの高さ合わせました〜
確認の方お願いします🙇

2022-06-30 07:06 UTC, kota78 commented on lib/components/user_page_article_list.dart
> +              ),
すみません、言葉足らずでした。そういうことです！

2022-06-30 07:22 UTC, kota78 commented
Readmeなのですが、フォルダのどこの階層に保存すればよいかを追記していただきたいです。
可能であれば写真などあるとわかりやすいかもしれません。
MacならShift+command+4で切り取りスクショが撮れます。
また、リンクも[こちら](https://flutter.dev/)のように示せると個人的には見やすいかなと感じます！
入力部分右上にある鎖のマーク(<>の右側)から使えます。

2022-06-30 12:01 UTC, kota78 commented
goodです！LGTM

2022-06-30 12:01 UTC, merged