設定画面の
shinonome-inc/flutter_app_qiita_ryunosuke pull request #21
Opened 2022-07-05 00:15 UTC by Ryunosuke1114

2022-07-05 00:18 UTC, Ryunosuke1114 commented
<img src='https://user-images.githubusercontent.com/85178728/177227607-3031629f-fcf7-48f2-981c-ad4ecd70fed6.png' width = 200>
設定画面のUIを実装しました。
お時間ある時にレビューお願いします🙇

2022-07-05 23:43 UTC, KobayashiYoh requested changes
コメントしました。

2022-07-05 23:43 UTC, KobayashiYoh commented on lib/components/setting_page_item_component.dart
> +      : super(key: key);
プロパティの定義が上手ですね👍

2022-07-05 23:43 UTC, KobayashiYoh commented on lib/components/setting_page_item_component.dart
> +          BoxDecoration(border: Border.all(color: const Color(0xFFE0E0E0))),
本当に```Border.all``` で大丈夫ですか？

2022-07-05 23:43 UTC, KobayashiYoh commented on lib/pages/setting_page.dart
> +              style: TextStyle(fontSize: 14.0, color: Colors.black),
アプリのバージョンを取得してくれるパッケージがあるので紹介しておきます（使用するかは任意）。
https://pub.dev/packages/package_info_plus

2022-07-05 23:43 UTC, KobayashiYoh commented on lib/pages/setting_page.dart
> +          )
未ログイン時はこのボタンを表示しない方がいいかもしれませんね。
ただ、修正は任意ですし、修正するとしてもログアウト機能実装時の方が良い気がするので今は何もしなくて大丈夫です。

2022-07-05 23:43 UTC, KobayashiYoh commented on lib/components/setting_page_item_component.dart
> +    return Container(
余白についてもう一度figmaを見直してみるといいかもしれませんね。
<img src="https://user-images.githubusercontent.com/82624334/177433671-65d151fe-ee14-4b15-b9b4-e6f88bec9668.png" width="300">

2022-07-06 00:12 UTC, KobayashiYoh reviewed
追加で1点だけコメントしました。

2022-07-06 00:12 UTC, KobayashiYoh commented on lib/components/setting_page_item_component.dart
> +  final String text;
ファイル名とクラス名は揃えた方がいいかもしれませんね。

2022-07-08 02:51 UTC, KobayashiYoh commented on lib/components/setting_page_item_component.dart
> +    return Container(
余白は本当にこれで大丈夫ですか？

2022-07-08 02:53 UTC, KobayashiYoh commented
1点だけコメントしました。https://github.com/shinonome-inc/flutter_app_qiita_ryunosuke/pull/21#discussion_r916421305

2022-07-08 03:13 UTC, KobayashiYoh approved these changes

2022-07-08 03:13 UTC, KobayashiYoh commented
LGTMです！
2次レビューに進んで下さい！

2022-07-08 23:37 UTC, ShuheiYoshidaJP commented
LGTMです。

2022-07-08 23:37 UTC, merged