ログアウト機能実装
shinonome-inc/flutter_app_qiita_ryunosuke pull request #23
Opened 2022-07-12 00:50 UTC by Ryunosuke1114

ログアウト機能を実装しました。
動作確認の動画は[こちら](https://gyazo.com/c4139474297982bdf9b2f6d9a8a6e2a1)からお願いします！
お時間ある時にレビューお願いします🙇

2022-07-12 00:52 UTC, Ryunosuke1114 commented
[fix : remove Authorization : Bearer](https://github.com/shinonome-inc/flutter_app_qiita_ryunosuke/pull/23/commits/d4b688064bafe8e3f700a56751622f70f798ecfd)

こちらはいログアウトした際にnullチェックでエラーを吐かれてしまって未ログイン次にFeedPageで記事を取得できなかったため取り除きました。

2022-07-12 07:09 UTC, Yoshida-koshi commented
OKです！
2次レビューを依頼してください！

2022-07-13 01:51 UTC, KobayashiYoh approved these changes
1点コメントしました。

2022-07-13 01:53 UTC, KobayashiYoh requested changes
間違えてApproveにしてしまいまったので修正

2022-07-13 07:28 UTC, KobayashiYoh approved these changes

2022-07-13 07:28 UTC, merged

2022-07-13 07:29 UTC, KobayashiYoh commented
LGTMです！
マージしました！